tasks:
  
  # this is a function task
  # "functions.clean" is equivalent to: from functions import clean
  - source: functions.tasks.load
    product: output/raw.csv

  - source: functions.tasks.clean
    product: output/clean.csv

  - source: functions.tasks.split
    product: 
      X_train: output/x_train.csv
      y_train: output/y_train.csv
      X_test: output/x_test.csv
      y_test: output/y_test.csv

  - source: functions.tasks.linear_regression
    product: output/coef.csv


  # # this is a script task (notebooks work the same)
  # - source: scripts/tasks/clean.py
  #   product:
  #     # scripts always generate a notebook (more on this in the next section)
  #     nb: output/clean.ipynb
